apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: apollo-portal-route
spec:
  hosts:
  - "apollo.sq.me"
  gateways:
  - http-gateway.istio-system.svc.cluster.local
  http:
  - match:
    - uri: 
        prefix: /
    route:
    - destination:
        host: apollo-portal
        subset: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: apollo-portal-dr
spec:
  host: apollo-portal
  subsets:
  - name: v1
    labels:
      version: v1.7

