apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  labels:
    app: jenkins
spec:
  type: NodePort
  selector: 
    app: jenkins
  ports:
    - port: 8080
      name: http
      protocol: TCP
      nodePort: 30000
      targetPort: 8080
    - port: 50000
      name: agent
      protocol: TCP
      targetPort: 50000

