apiVersion: v1
kind: Service
metadata:
  name: sonar-service
  labels:
    app: sonar
spec:
  type: NodePort
  selector: 
    app: sonar
  ports:
    - port: 9000
      name: http
      protocol: TCP
      nodePort: 30001
      targetPort: 9000

