apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonar-deployment
  labels:
    app: sonar
spec:
  selector:
    matchLabels:
      app: sonar
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sonar
    spec:
      containers:
        - image: sonarqube
          name: sonar-container
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: sonar-persistentstorage
              mountPath: /opt/sonarqube/data
      volumes:
        - name: sonar-persistentstorage
          persistentVolumeClaim:
            claimName: sonar-pvclaim
            
